### PR TITLE
7 fix non cran dependency issue

### LINKED ISSUE #7: Running the app gives error Warning: Error in loadNamespace: there is no package called ‘nhsrtheme’ in the chart
I searched for references to {nhsrtheme}, and found only these 2. Does {nhsrtheme} need added to the imports or depends perhaps?

EDIT: I see that having {nhsrtheme} specified in the remotes is supposed to handle importing it. So I am not sure what is causing the error after all.

image

### PR DESCRIPTION
**Pull request by ghost**
Closes #7 

Issue with failing to install non-cran dependencies from the DESCRIPTION file

### CODE REVIEW

**Comment by ghost** [comment]
@MarkMc1089 could you please try this again? The package has changed it's name to uppercase so didn't work. Fixed now though and tested. It seems like the Remotes method works after all!

> devtools::install_github(repo = "nhsbsa-data-analytics/nhsbsaR", ref = "7-fix-non-cran-dependency-issue")
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
Downloading GitHub repo nhsbsa-data-analytics/nhsbsaR@7-fix-non-cran-dependency-issue
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                      
 2: CRAN packages only                       
 3: None                                     
 4: rlang       (0.4.11   -> 0.4.12  ) [CRAN]
 5: lifecycle   (1.0.0    -> 1.0.1   ) [CRAN]
 6: cpp11       (0.3.1    -> 0.4.1   ) [CRAN]
 7: generics    (0.1.0    -> 0.1.1   ) [CRAN]
 8: digest      (0.6.27   -> 0.6.28  ) [CRAN]
 9: crayon      (1.4.1    -> 1.4.2   ) [CRAN]
10: cli         (2.4.0    -> 3.1.0   ) [CRAN]
11: pillar      (1.6.2    -> 1.6.4   ) [CRAN]
12: tidyselect  (1.1.0    -> 1.1.1   ) [CRAN]
13: tibble      (3.1.0    -> 3.1.5   ) [CRAN]
14: dplyr       (1.0.5    -> 1.0.7   ) [CRAN]
15: curl        (4.3      -> 4.3.2   ) [CRAN]
16: colorspace  (2.0-0    -> 2.0-2   ) [CRAN]
17: viridisLite (0.3.0    -> 0.4.0   ) [CRAN]
18: stringi     (1.5.3    -> 1.7.5   ) [CRAN]
19: withr       (2.4.1    -> 2.4.2   ) [CRAN]
20: isoband     (0.2.4    -> 0.2.5   ) [CRAN]
21: ggplot2     (3.3.3    -> 3.3.5   ) [CRAN]
22: tidyr       (1.1.2    -> 1.1.4   ) [CRAN]
23: backports   (1.2.0    -> 1.3.0   ) [CRAN]
24: data.table  (1.13.2   -> 1.14.2  ) [CRAN]
25: XML         (3.99-0.6 -> 3.99-0.8) [CRAN]
26: htmltools   (0.5.1.1  -> 0.5.2   ) [CRAN]
27: hms         (0.5.3    -> 1.1.1   ) [CRAN]
28: DBI         (1.1.0    -> 1.1.1   ) [CRAN]
29: blob        (1.2.1    -> 1.2.2   ) [CRAN]
30: lubridate   (1.7.9    -> 1.8.0   ) [CRAN]
31: igraph      (1.2.6    -> 1.2.7   ) [CRAN]
32: broom       (0.7.4    -> 0.7.10  ) [CRAN]
33: rlist       (0.4.6.1  -> 0.4.6.2 ) [CRAN]
34: htmlwidgets (1.5.3    -> 1.5.4   ) [CRAN]
35: dbplyr      (2.0.0    -> 2.1.1   ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
Downloading GitHub repo nhs-r-community/NHSRtheme@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                   
 2: CRAN packages only                    
 3: None                                  
 4: stringi     (1.5.3   -> 1.7.5 ) [CRAN]
 5: highr       (0.8     -> 0.9   ) [CRAN]
 6: rlang       (0.4.11  -> 0.4.12) [CRAN]
 7: digest      (0.6.27  -> 0.6.28) [CRAN]
 8: jquerylib   (0.1.3   -> 0.1.4 ) [CRAN]
 9: xfun        (0.26    -> 0.28  ) [CRAN]
10: tinytex     (0.34    -> 0.35  ) [CRAN]
11: htmltools   (0.5.1.1 -> 0.5.2 ) [CRAN]
12: knitr       (1.31    -> 1.36  ) [CRAN]
13: later       (1.1.0.1 -> 1.3.0 ) [CRAN]
14: httpuv      (1.5.5   -> 1.6.3 ) [CRAN]
15: mime        (0.10    -> 0.12  ) [CRAN]
16: colorspace  (2.0-0   -> 2.0-2 ) [CRAN]
17: viridisLite (0.3.0   -> 0.4.0 ) [CRAN]
18: lifecycle   (1.0.0   -> 1.0.1 ) [CRAN]
19: crayon      (1.4.1   -> 1.4.2 ) [CRAN]
20: cli         (2.4.0   -> 3.1.0 ) [CRAN]
21: pillar      (1.6.2   -> 1.6.4 ) [CRAN]
22: rmarkdown   (2.7     -> 2.11  ) [CRAN]
23: servr       (0.21    -> 0.23  ) [CRAN]
24: withr       (2.4.1   -> 2.4.2 ) [CRAN]
25: tibble      (3.1.0   -> 3.1.5 ) [CRAN]
26: isoband     (0.2.4   -> 0.2.5 ) [CRAN]
27: tidyselect  (1.1.0   -> 1.1.1 ) [CRAN]
28: generics    (0.1.0   -> 0.1.1 ) [CRAN]
29: xaringan    (0.20    -> 0.22  ) [CRAN]
30: ggplot2     (3.3.3   -> 3.3.5 ) [CRAN]
31: dplyr       (1.0.5   -> 1.0.7 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\adaiv\AppData\Local\Temp\RtmpIxxCaF\remotes59907e165c81\nhs-r-community-NHSRtheme-e4776f0/DESCRIPTION' (776ms)
-  preparing 'NHSRtheme': (970ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'NHSRtheme_0.1.0.tar.gz'
   
* installing *source* package 'NHSRtheme' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'NHSRtheme'
    finding HTML links ... done
    NHSRtheme                               html  
    get_nhs_colour_tints                    html  
    get_nhs_colours                         html  
    get_nhs_palette                         html  
    scale_colour_nhs                        html  
    scale_fill_nhs                          html  
    show_nhs_theme_colour_tints             html  
    show_nhs_theme_colours                  html  
    theme_nhs                               html  
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (NHSRtheme)
Skipping install of 'NHSRtheme' from a github remote, the SHA1 (e4776f0b) has not changed since last install.
  Use `force = TRUE` to force installation
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\adaiv\AppData\Local\Temp\RtmpIxxCaF\remotes599044ae2111\nhsbsa-data-analytics-nhsbsaR-e0e14f9/DESCRIPTION' (670ms)
-  preparing 'nhsbsaR': (357ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'nhsbsaR_0.0.0.9000.tar.gz'
   
* installing *source* package 'nhsbsaR' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'nhsbsaR'
    finding HTML links ... done
    con_nhsbsa                              html  
    oracle_unnest_tokens                    html  
    palette_nhsbsa                          html  
    pool_nhsbsa                             html  
    scale_colour_nhsbsa                     html  
    scale_fill_nhsbsa                       html  
    theme_nhsbsa_gg                         html  
    theme_nhsbsa_hc                         html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (nhsbsaR)

**Comment by nhsbsa-kaygo** [comment]
I have **removed** both **nhsrtheme** and **nhsbsaR** packages and **restart R**. (make sure check in library folder (.libPath()) whether they have removed)

**devtools::install_github(repo = "nhsbsa-data-analytics/nhsbsaR", ref = "7-fix-non-cran-dependency-issue")** 

It reinstalled NHSRtheme and nhsbsaR packages and working fine.

**Comment by nhsbsa-mamcp** [comment]
`devtools::install_github(repo = "nhsbsa-data-analytics/nhsbsaR", ref = "7-fix-non-cran-dependency-issue")` works for me too.

But, when I try to do the same for my forked version, I get the error:
`ERROR: dependency 'nhsrtheme' is not available for package 'nhsbsaR'`

Somewhere it is still looking for the lower case `nhsrtheme`, even tho I have replaced it with the correct `NHSRtheme` everywhere it appears in my code. Any idea what I might have missed?

Other than that issue, this should be ready to merge now.

**Comment by nhsbsa-mamcp** [comment]
Sorry, meant to add that comment on the other PR...

**Pull request merged**
